### ISSUE TITLE
Add new SymfonyCacheableInterceptor that interacts with Symfony pool manager

### ISSUE THREAD

**Issue by insekticid** [phpro/annotated-cache#2]
Phpro\AnnotatedCache\Interceptor\CacheableInterceptor::interceptSuffix returns Cache\Adapter\Common\CacheItem;

but Symfony\Component\Cache\Adapter interacts only with Symfony\Component\Cache\CacheItem otherwise will skip save to cache

@see Symfony\Component\Cache\Adapter\AbstractAdapter::save()
```
    public function save(CacheItemInterface $item)
    {
        if (!$item instanceof CacheItem) {
            return false;
        }
        $this->deferred[$item->getKey()] = $item;

        return $this->commit();
    }
```

Or there should be fix on Symfony side in this method? 

Edit: Symfony is logging some debug info via static method CacheItem::log, thats missing in standardized Cache\Adapter\Common\CacheItem;

Edit2: I have created new SymfonyInterceptor
https://github.com/insekticid/phpro-annotated-cache-symfony-cache

**Comment by veewee** [comment]
Hi @insekticid,

Thanks for reporting!

Currently we are using the https://github.com/php-cache packages.
This is because the symfony PSR-6 cache component was added in 3.1 and this package was created in the time of 2.8 if I remember correctly.

In my opinion, the cache component of Symfony is implemented in a bad way. I am sure that they had their reasons to only support their own cache item like e.g. that additional log method. This makes their component not interoperatable with other PSR-6 libraries. Also: if you follow SOLID principles, this breaks the substitution principle of Liskov.

Maybe it's better to report this issue in the Symfony Component package?
An alternative could be a factory which can be inserted into our CacheableInterceptor. That way you can specify how a cache item can be created. However: I would prefer to have the Symfony package allowing multiple CacheItem implementations.

Your feedback on the topic is more then welcome :)

**Comment by insekticid** [comment]
fixed in pull #3

**Comment by veewee** [comment]
Hi @insekticid,

Did you try the https://github.com/php-cache/doctrine-bridge package?
Since the Symfony cache component uses the doctrine CacheProvider, it might work for your case.

Since we expect that every package implementing PSR-6 should work the same and do not want to support X amount of  different PSR-6 implementations, it seems like a better idea to use or write a bridge for the Symfony cache component.

**Comment by insekticid** [comment]
Good hint. I will try it. Thanks
